### ISSUE TITLE
using this template in tex-studio

### ISSUE THREAD

**Issue by avigliotti** [roaldarbol/LaPreprint#12]
Hi,

I am using tex-studio for writing documents, how can install this template and use it from tex-studio in linux and windows?

thanks in advance,
Andrea

**Comment by dangom** [comment]
This should work (untested):

```sh
git clone https://github.com/roaldarbol/LaPreprint.git
cd LaPreprint
TEXMFHOME=$(kpsewhich -var-value TEXMFHOME)
mkdir "$TEXMFHOME"/tex/latex/base
cp lapreprint.cls "$TEXMFHOME"/tex/latex/base
sudo texhash
```
And then use class lapreprint for your document.

**Comment by hvoss49** [comment]
I'd use `TEXMFLOCAL=$(kpsewhich -var-value TEXMFLOCAL)`  instead

**Comment by roaldarbol** [comment]
I've never used TexStudio, so I can't help. Sounds like @dangom and @hvoss49 has a good idea of how. Once it's been tested out I can add it to the wiki.

**Comment by hvoss49** [comment]
The used editor is not important. It is the same for _all_ editors: save the files which are _not_ part of the TeX distribution (TeXLive or MiKTeX) into your local directory which can be `TEXMFHOME -> <userdir>/texmf/...` or `TEXMFLOCAL->/usr/local/texlive/texmf-local/...`.  For Windows and MiKTeX it is slightly different, you have to tell MiKTeX vis the preferences where your local files are saved.

Foe all cases you have to update after saving the files the "file name data base" by running in a terminal `texhash` or for MiKTeX clicking on the update button in the preferences menue.
