### ISSUE TITLE
doi is colored depending on format

### ISSUE THREAD

**Issue by bforsbe** [roaldarbol/LaPreprint#20]
It appears as if the doi field of a bib entry has a period after the forward slash, it is colored as a url. If not, it isn't colored. I tried to see how this was determined, but I couldn't work it out. 

![Screenshot from 2022-11-03 20-00-55](https://user-images.githubusercontent.com/7627666/199822468-78124371-9a91-4a7d-94ba-ce39eabdcae8.png)

**Comment by hvoss49** [comment]
provide the bib data file for testing.

**Comment by bforsbe** [comment]
Had to zip it, .bib was not a permitted file type to attach 
[Cryo-EM-OCC.zip](https://github.com/roaldarbol/LaPreprint/files/9933212/Cryo-EM-OCC.zip)

**Comment by hvoss49** [comment]
I cannot see it with `style=authortitle`. 

<img width="441" alt="Bildschirm­foto 2022-11-04 um 11 46 03" src="https://user-images.githubusercontent.com/12891199/199954755-799c37db-185f-406a-b5a2-4c0ce126396f.png">

However, you should comment the first lines in your bibfile, that are only comments. And you have a lot of warnings:

```biber --validate_datamodel <file>```

**Comment by hvoss49** [comment]
And the same with Vancouver style together with. aithortitle:

<img width="648" alt="Bildschirm­foto 2022-11-04 um 12 19 01" src="https://user-images.githubusercontent.com/12891199/199961099-95574f93-38fa-4cbd-885e-bfd44916325f.png">

**Comment by roaldarbol** [comment]
Hi @bforsbe! Thanks for the report. I updated from bibtex to biber a few days ago - can you try to see if the problem persists with the latest version? I currently cannot reproduce the problem either. Thanks for testing out the template!

**Comment by bforsbe** [comment]
This was on overleaf, that might be part of the reason. I'll try with biber when I get a chance.

**Comment by bforsbe** [comment]
Actually had a go now and it works fine with the most recent commit 87b5fd8
