### ISSUE TITLE
Support small caps command

### ISSUE THREAD

**Issue by tushartushar** [roaldarbol/LaPreprint#25]
It seems, currently the template doesn't support `{\sc text}` or `\textsc{text}`.

**Comment by hvoss49** [comment]
`\sc`  is deprecated syntax and for small caps choose a font which has it, eg `\usepackage{libertinus}`

**Comment by roaldarbol** [comment]
Hi @tushartushar, thanks for the issue. As @hvoss49 mentioned, the default font doesn't support small caps. There is a workaround, to use the sans serif font: `\textsf{\textsc{this works}}`.
However, I think it also points to a different issue I've been considering, that there should be an easy way to change the default font - I'll create a new issue for that. 👍

**Comment by tushartushar** [comment]
Thanks a lot for looking into it and offering alternatives.
