### ISSUE TITLE
Add annotated equations

### ISSUE THREAD

**Issue by roaldarbol** [roaldarbol/LaPreprint#27]
Annotated equations are great for making equations more readable and accessible - add support: https://ctan.org/pkg/annotate-equations.

**Comment by da5nsy** [comment]
I've recently implemented this in a document which uses this template, let me know if you'd like me to contribute to this

**Comment by roaldarbol** [comment]
Hey @da5nsy! Yes please, that would be much appreciated - just make a pull request then I'll have a look at it!
