### ISSUE TITLE
Suggestion: put a link to the repo in the readme

### ISSUE THREAD

**Issue by da5nsy** [roaldarbol/LaPreprint#29]
... so that when people clone it, use it, share it, people know where to come back to for a clean copy 😄 

Might be worth adding a version number in the same place, if you think that's a good idea? 
Or perhaps combine the two and just have a [permalink](https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files#press-y-to-permalink-to-a-file-in-a-specific-commit)?

**Comment by roaldarbol** [comment]
Good idea - there's of course the link in the output document, but I do see the benefit of having in the README as well. I think I'll wait with version numbers until I get around to uploading on CTAN, but then it'll make sense to include. 😊
