### ISSUE TITLE
Margin notes only show up if abstract is included

### ISSUE THREAD

**Issue by da5nsy** [roaldarbol/LaPreprint#30]
Presumably there will almost always be an abstract, but just FYI

**Comment by roaldarbol** [comment]
Ah yes, that's true. This is to properly align the margin notes, as they will otherwise begin from either the title or the main text. If you figure out a solution that manages to do the same without relying on it to be done alongside the abstract I'd be happy to make that work.

**Comment by da5nsy** [comment]
I can't see anything obvious...

**Comment by roaldarbol** [comment]
Any obvious differences or alternatives?😅

**Comment by da5nsy** [comment]
As in - I can't see any easy fixes, and it isn't a major issue so I'll close this but I'll let you know if I think of a nice solution 😊
