### ISSUE TITLE
biblatex showing "visited on", and language, in the bibliography

### ISSUE THREAD

**Issue by da5nsy** [roaldarbol/LaPreprint#31]
https://tex.stackexchange.com/a/400385/169285
https://tex.stackexchange.com/a/401026/169285

I would recommend adding:
```
\AtEveryBibitem{
    \clearfield{urlyear}
    \clearfield{urlmonth}
    \clearlist{language}
}
```
somewhere so that these are not included in the bibliography if they are in the `.bib` file

**Comment by roaldarbol** [comment]
Ah, cool, thanks for finding that - I'll add that. :-)
