### ISSUE TITLE
Sidenote overlap with fullwidth figures

### ISSUE THREAD

**Issue by tomdemeyere** [roaldarbol/LaPreprint#45]
Hi, thanks for your work on this,

Any easy way to move sidenotes up and down? I have a case where it overlaps with a fullwidth figure

**Comment by roaldarbol** [comment]
Uh, not that I know of unfortunately. That is all taken care of by the `snotez` package. I can have a look when I find time sometime in the coming weeks to figure out whether there is a workaround.

**Comment by tomdemeyere** [comment]
Yes! Sorry, I didn't realize that was from a package. I found how to do it we can close that

Thanks for your work btw.

**Comment by roaldarbol** [comment]
Ah, brilliant, glad to hear that. Just for our future selves, how did you solve it? :-)

**Comment by tomdemeyere** [comment]
https://eu.mirrors.cicku.me/ctan/macros/latex/contrib/snotez/snotez-manual.pdf has everything relevant. 

For my case that was:
\sidenote[][-50mm]
