### ISSUE TITLE
Support Typst 0.12

### ISSUE THREAD

**Issue by JeppeGivskud** [roaldarbol/LaPreprint#46]
I'm not sure if it is okay to create a new issue but i cannot get some of the locate functions to not cast warnings.

Message:
`locate` with callback function is deprecated

Hint: use a `context` expression instead

Code:
```
  set page(
    paper-size,
    margin: (left: 25%),
    header: locate(loc => {
      if(loc.page() == 1) {
        let headers = (
          if (open-access) {smallcaps[Open Access]},
          if (doi != none) { link("https://doi.org/" + doi, "https://doi.org/" + doi)}
        )
        return align(left, text(size: 8pt, fill: gray, headers.filter(header => header != none).join(spacer)))
      } else {
        return align(right, text(size: 8pt, fill: gray.darken(50%),
          (short-title, short-citation).join(spacer)
        ))
      }
    }),

....more code.....
```

**Comment by roaldarbol** [comment]
Hi @JeppeGivskud! 
Thanks for the report! It seems to already be tracked in the typst repository: https://github.com/LaPreprint/typst/issues/7 😊 This repository is for the original LaTeX version.

**Comment by JeppeGivskud** [comment]
Oh I'm so sorry haha. Thanks for the fast reply though!
